apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openstack-hypervisor-operator.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "openstack-hypervisor-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "openstack-hypervisor-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "openstack-hypervisor-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args: {{- toYaml .Values.controllerManager.manager.args | nindent 8 }}
        env:
        - name: OS_AUTH_URL
          value: {{ quote .Values.controllerManager.manager.env.osAuthUrl }}
        - name: OS_PROJECT_DOMAIN_NAME
          value: {{ quote .Values.controllerManager.manager.env.osProjectDomainName }}
        - name: OS_PROJECT_NAME
          value: {{ quote .Values.controllerManager.manager.env.osProjectName }}
        - name: OS_REGION_NAME
          value: {{ quote .Values.controllerManager.manager.env.osRegionName }}
        - name: OS_USER_DOMAIN_NAME
          value: {{ quote .Values.controllerManager.manager.env.osUserDomainName }}
        - name: OS_USERNAME
          value: {{ quote .Values.controllerManager.manager.env.osUsername }}
        - name: OS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SERVICE_PASSWORD
              name: {{ include "openstack-hypervisor-operator.fullname" . }}-secret
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.controllerManager.manager.containerSecurityContext
          | nindent 10 }}
      nodeSelector: {{- toYaml .Values.controllerManager.nodeSelector | nindent 8 }}
      securityContext: {{- toYaml .Values.controllerManager.podSecurityContext | nindent
        8 }}
      serviceAccountName: {{ include "openstack-hypervisor-operator.serviceAccountName"
        . }}
      terminationGracePeriodSeconds: 10
      tolerations: {{- toYaml .Values.controllerManager.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.controllerManager.topologySpreadConstraints
        | nindent 8 }}
